version: 2.1
jobs:
  build-and-deploy:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
    - checkout
    - run:
        command: |
            docker build -t $DOCKER_LOGIN/$IMAGE_NAME -t $DOCKER_LOGIN/$IMAGE_NAME:$CIRCLE_BUILD_NUM-$CIRCLE_BRANCH .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/$IMAGE_NAME
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy 
